FROM oven/bun:1-alpine
WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY drizzle.config.ts ./
COPY .env ./
COPY server ./server

USER bun
CMD ["bun", "server/workers/index.ts"]
